### PR TITLE
Add Copyright properties to the response

### PR DESCRIPTION
**Pull request by jesusalvino**
### Purpose

Add the Copyright properties to the Package version response in order to be consumed in the UI like Dynamo

### Declarations

Check these if you believe they are true

- [x] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers
@QilongTang

### FYIs
@RobertGlobant20 @filipeotero

### CODE REVIEW

**Comment by zeusongit** [comment]
Did you also publish updated Nuget packages with this change?
I see the last published package was 4 days ago https://www.nuget.org/packages/Greg/2.1.8117.36056

**Comment by jesusalvino** [comment]
> @jesusalvino Did you also publish updated Nuget packages with this change? I see the last published package was 4 days ago https://www.nuget.org/packages/Greg/2.1.8117.36056

No yet, per my understand it's automatic once this PR is approved, if there is something pending from my side please let me know

**Comment by QilongTang** [comment]
@zeusongit is the publish manual? I thought it was covered by CI? Maybe @pinzart and @sm6srw would know

**Comment by zeusongit** [comment]
> @zeusongit is the publish manual? I thought it was covered by CI? Maybe @pinzart and @sm6srw would know

I remember publishing nugets last time I updated greg client, but I guess that was for local testing, I think there probably is a CI job for this, sorry for the confusion.

**Review by zeusongit — APPROVED** [review]

**Review by QilongTang — APPROVED** [review]

**Pull request merged**
