### PR TITLE
add net45 targeting to Greg.dll so we can consume latest fixes in older Dynamo versions

### PR DESCRIPTION
**Pull request by mjkkirschner**
Screen Shot 2019-05-09 at 3 15 13 PM

This PR adds a new project to the package manager client solution - 
a legacy GregClient_net45 project. This is not ideal. 

At first I tried to use the `<targetFrameworks>` attribute as described here:
https://docs.microsoft.com/en-us/dotnet/standard/frameworks

sounds great .... it's not so simple of course - nuget restore is immediately busted. The solution crashes VS 2017(latest updates) whenever you try to clean or rebuild the solution. I found a few github issues reporting similar things from last year. If this was a project we updated more or if we intended to have more multi targeting I might look further, but I'm just not sure this feature of csproj files works very well with vs yet.

Instead I just added this extra project - it links to all the existing files of the regular GregClient.csproj, but targets `net45`.

I added a `globalAssemblyVersion.cs` file so the version numbers of both dlls are the same -

I also added some copy and rename steps to the nuget pack script to create a `net45` folder with this dll.

⚠️ TODO:

- [x] I have not yet tried actually importing / referencing this dll from Dynamo/DynamoRevit which is what I will need to do next to verify this works.

### Reviewers:
@aparajit-pratap 
@scottmitchell

### CODE REVIEW

**Comment by aparajit-pratap** [comment]
@mjkkirschner which old versions of Dynamo/D4R need to consume the latest fixes? Can you remind me which version of Dynamo had the target fx updated to net47.

**Comment by mjkkirschner** [comment]
This patch is intended for 2.0.3 - Dynamo 2.1 switched to .net 4.7

**Comment by aparajit-pratap** [comment]
lgtm

**Comment by scottmitchell** [comment]
@mjkkirschner If this change will only ever be necessary in 2.0.x, is it worth creating a `2.0Legacy` branch rather than merging these changes to `master`? Or maybe this idea ultimately complicates things further—just a thought.

**Comment by mjkkirschner** [comment]
@scottmitchell - thats another way to go - I think we will discover that future bug fixes we need to make -will be useful to backport - having only one copy of the code here will make that easier. At the same time I think this is a useful example to have around for what will need to be done when we want to multi target other parts of our ecosystem - ie Dynamo itself.

IMO What we should do is branch this repo whenever we change the API here - which so far has not been done.

**Comment by mjkkirschner** [comment]
made a small change here to avoid renaming the dll - now the net45 stuff builds into a net 45 folder and is copied from there - no renaming or removing dlls required and no reference errors later.

consuming this change here:
https://github.com/DynamoDS/Dynamo/pull/9718

**Comment by aparajit-pratap** [comment]
LGTM!

**Comment by scottmitchell** [comment]
LGTM

**Pull request merged**
