### PR TITLE
Update GregClient.nuspec

### PR DESCRIPTION
**Pull request by zeusongit**
Adding MIT license expression

### CODE REVIEW

**Comment by QilongTang** [comment]
@zeusongit Do we need to touch nuspec file as well to reflect this?

**Comment by zeusongit** [comment]
GregClient.nuspec is where the expression is added, we don't have to change anything else, this was a part of the previous commit but was left out.

**Comment by mjkkirschner** [comment]
did you have any trouble building this @zeusongit ?
I am getting:
```
2>  The element 'metadata' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd' has invalid child element 'license' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'. List of possible elements expected: 'projectUrl, summary, contentFiles, references, licenseUrl, packageTypes, serviceable, developmentDependency, frameworkAssemblies, iconUrl, language, repository' in namespace 'http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd'. This validation error occurred in a 'license' element.
```

**Comment by zeusongit** [comment]
I am able to build successfully

**Comment by zeusongit** [comment]
Readme updated with a note to have Nuget 4.9.0 or later.

**Comment by mjkkirschner** [comment]
@zeusongit LGTM

**Pull request merged**
