### PR TITLE
Adding Host Dependencies

### PR DESCRIPTION
**Pull request by QilongTang**
Adding host dependencies into the Greg C# Client so user would be able to upload package with host_dependencies specified. This is required by https://jira.autodesk.com/browse/DYN-1979.

FYI: @pinzart

### CODE REVIEW

**Comment by mjkkirschner** [comment]
what about incrementing the version number and branching now as well?

**Comment by QilongTang** [comment]
@mjkkirschner Will add that part later, I need to run this part with heavy testing and more thinking. I am still not convinced `host_dependencies` need to be a list but kind worried about the AutoCAD vertical cases which may require the list case.

**Comment by gregmarr** [comment]
I could easily see "this package runs on AutoCAD and Civil3D but not Revit", making this an "any of" list.

**Comment by QilongTang** [comment]
@gregmarr Agree, I think list between Revit and ACAD would be seldom to see, but between ACAD verticals makes lot of sense. I would love to run through this PR with you and @pinzart at some point. I will also open a separate PR in Dynamo to consume the changes here

**Comment by mjkkirschner** [comment]
@QilongTang to test this just push it to a local nuget repo:
https://medium.com/@churi.vibhav/creating-and-using-a-local-nuget-package-repository-9f19475d6af8

**Comment by QilongTang** [comment]
Updated minor version, I expect we do all the development on the host depedencies area in v1.2

**Pull request merged**
