### PR TITLE
[DYN-2776] Remove DotNetZipLib-DevKit-v1.9

### PR DESCRIPTION
**Pull request by Astul-Betizagasti**
### Purpose

Removes DotNetZipLib DevKit to reduce vulnerabilities 

### Declarations

Check these if you believe they are true

- [ ] The codebase is in a better state after this PR
- [ ] Is documented according to the [standards](https://github.com/DynamoDS/Dynamo/wiki/Coding-Standards)
- [ ] The level of testing this PR includes is appropriate
- [ ] Changes to the API follow [Semantic Versioning](https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Versions) and are documented in the [API Changes](https://github.com/DynamoDS/Dynamo/wiki/API-Changes) document.

### Reviewers

Aaron Tang (@QilongTang )
Michael Kirschner (@mjkkirschner )

### FYIs

Alfredo Pozo (@alfredo-pozo )

### CODE REVIEW

**Comment by QilongTang** [comment]
@Astul-Betizagasti How to we reflect this change on WS dashboard?

**Comment by alfredo-pozo** [comment]
@QilongTang It will be reflected after the pipeline runs again with the new changes and we can see that on the WS dashboard the warning related to that library won't appear

**Comment by QilongTang** [comment]
@alfredo-pozo Understood. I guess I am curious when it will run again, is it per build or per month now?

**Comment by alfredo-pozo** [comment]
@QilongTang  On both

**Comment by QilongTang** [comment]
@alfredo-pozo Cool. Thx!

**Pull request merged**
